# Legacy Issues
Metrics/BlockNesting:
  Exclude:
  - 'providers/certificate.rb'

Style/GuardClause:
  Exclude:
  - 'providers/certificate.rb'

# remove/change once https://github.com/chef/cookstyle/issues/28
# is resolved:
Style/DoubleNegation:
  Exclude:
  - 'resources/persistence.rb'
